version: "3"

services:
  reverse-proxy:
    image: nginx
    container_name: api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  api:
    image: api:1.0
    build:
      context: ./app
      dockerfile: Dockerfile